### ISSUE TITLE
Please add WeACT MiniF4 F401CCU6

### ISSUE THREAD

**Issue by leech001** [JojoS62/custom_targets#1]
Please add WeACT MiniF4 F401CCU6 in custom target for MBED.

**Comment by JojoS62** [comment]
yes, I will check it, but have no F401 board for testing.

**Comment by JojoS62** [comment]
Meanwhile, this target is added. I have not run all tests, but basic stuff incl. USB is working.

**Comment by leech001** [comment]
Thank you so much. I keep track of your project.
Please only specify which version was added as a result STM32F401CCU6 or STM32F401CEU6.

**Comment by JojoS62** [comment]
the Weact **F401** board has the STM32F401CCUx, the **F411** has the STM32F411CEUx MCU. These are the options that I found for this board, both can be used.

**Comment by leech001** [comment]
> the Weact **F401** board has the STM32F401CCUx, the **F411** has the STM32F411CEUx MCU. These are the options that I found for this board, both can be used.

Not quite right statement. Since June, the founders of the project switched from version 3.0 to STM32F401CE.
The actual quote is from the source "2020.06 , STM32F401CC V3.0 End Of Life , Replace With STM32F401CE V3.0 (84Mhz, 512KB ROM, 96KB RAM).If the online shopping platform still sells STM32F401CCU6, it is fake!!".
The project itself [https://github.com/WeActTC/MiniF4-STM32F4x1](https://github.com/WeActTC/MiniF4-STM32F4x1)

**Comment by JojoS62** [comment]
Thanks for the update. I have checked my modules, the MCU has a date code 912, should be very new. This board is also working fine, although it has no WeAct Label on the bottom.
I have added the F401CE variant to the repo. It compiles, but I cannot test it on the real hardware.
