### ISSUE TITLE
custom_targets for Mbed 6

### ISSUE THREAD

**Issue by andy-hopkins** [JojoS62/custom_targets#2]
Will you be updating custom_targets to work with mbed studio 1 and mbed 6.0 ?

Cheers

**Comment by JojoS62** [comment]
sorry, did not check this repos for some time.
Yes, I'm also using Mbed6 and have updated some settings that are different now.
It works als with MbedStudio, but there custom_targets.json needs to be copied into the project root as just discussed in
https://forums.mbed.com/t/lpc812-support/9096/18
